package cn.it.shop.model;
// Generated 2019-4-11 20:16:58 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Forder generated by hbm2java
 */
public class Forder implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private String remark;
	private Date date;
	private BigDecimal total;
	private String post;
	private String address;
	private User user;
	private Status status;
	private Set<Sorder> sorderSet = new HashSet<>();

	public Forder() {
	}
	
	public Forder(Set<Sorder> sorderSet) {
		super();
		this.sorderSet = sorderSet;
	}


	public Forder(Integer id, String name, String phone, String remark, Date date, BigDecimal total, String post,
			String address, User user, Set<Sorder> sorderSet) {
		super();
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.remark = remark;
		this.date = date;
		this.total = total;
		this.post = post;
		this.address = address;
		this.user = user;
		this.sorderSet = sorderSet;
	}
	
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<Sorder> getSorderSet() {
		return sorderSet;
	}

	public void setSorderSet(Set<Sorder> sorderSet) {
		this.sorderSet = sorderSet;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}


}
