package cn.it.shop.model;
// Generated 2019-4-11 20:16:58 by Hibernate Tools 5.3.0.Beta2

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer id;
	private String status;

	public Status() {
	}

	public Status(Integer id) {
		super();
		this.id = id;
	}




	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
